### ISSUE TITLE
如何用python3？

### ISSUE THREAD

**Issue by sunfeng90** [samrayleung/jd_spider#12]
我用scrapy crawl jindong，结果用的是系统的python 2.7，而不是python3.用什么命令可以用python3啊？

**Comment by sunfeng90** [comment]
谢谢，我目前还没有跑起来，报各种错误。可以加你的微信或者QQ吗？想线下请假你

**Comment by sunfeng90** [comment]
上面的问题，我通过更新scrapy解决了。目前无法获取redis，可是我安装了redis。File "/Library/Frameworks/Python.framework/Versions/3.6/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/commands/shell.py", line 65, in run
    crawler = self.crawler_process._create_crawler(spidercls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 203, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 41, in __init__
    self.stats = load_object(self.settings['STATS_CLASS'])(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lcs/Frank-Project/python/jd_spider/jd/jd/statscol/graphite.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis' 默认好像安装到python2中。

**Comment by samrayleung** [comment]
解决方法还是virtualenv, 你需要将单个项目安装的library 和系统全局的library 隔离开。如果你不了解vritualenv, 建议你先了解一下 virtualenv

**Comment by sunfeng90** [comment]
Thks

**Comment by sunfeng90** [comment]
FrankdeMacBook-Pro:jd sunfeng$ pwd
/Users/sunfeng/Project/Python/demo/jd_spider/jd
FrankdeMacBook-Pro:jd sunfeng$ ls
jd		scrapy.cfg
FrankdeMacBook-Pro:jd sunfeng$ virtualenv -p python3 env
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/sunfeng/Project/Python/demo/jd_spider/jd/env/bin/python3
Also creating executable in /Users/sunfeng/Project/Python/demo/jd_spider/jd/env/bin/python
Installing setuptools, pip, wheel...done.
FrankdeMacBook-Pro:jd sunfeng$ source env/bin/activate
(env) FrankdeMacBook-Pro:jd sunfeng$ scrapy crawl jindong
Traceback (most recent call last):
  File "/Users/sunfeng/anaconda2/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/Users/sunfeng/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/sunfeng/Project/Python/demo/jd_spider/jd/jd/spiders/jd.py", line 6, in <module>
    from urllib import parse
ImportError: cannot import name parse
(env) FrankdeMacBook-Pro:jd sunfeng$

**Comment by sunfeng90** [comment]
@samrayleung 上面是我的操作，默认使用了Python2.7，而不是python3

**Comment by sunfeng90** [comment]
(env) FrankdeMacBook-Pro:jd sunfeng$ scrapy -v
Scrapy 1.5.0 - project: jd

**Comment by sunfeng90** [comment]
貌似我用了virtualenv,也安装了redis,但是还是提示找不到redis.

`(venv) lcsdeMac-mini:jd lcs$ scrapy crawl jindong
2018-04-17 09:26:59 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: jd)
2018-04-17 09:26:59 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) - [GCC 4.2.1 (AppleInc. build 5666) (dot 3)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-17.5.0-x86_64-i386-64bit
2018-04-17 09:26:59 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'jd', 'CONCURRENT_REQUESTS': 32, 'CONCURRENT_REQUESTS_PER_DOMAIN': 16, 'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter', 'NEWSPIDER_MODULE': 'jd.spiders', 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'SPIDER_MODULES': ['jd.spiders'], 'STATS_CLASS': 'jd.statscol.graphite.RedisGraphiteStatsCollector'}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 170, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 198, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 203, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 41, in __init__
    self.stats = load_object(self.settings['STATS_CLASS'])(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/lcs/Frank-Project/python/jd_spider/jd/jd/statscol/graphite.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
(venv) lcsdeMac-mini:jd lcs$`

`virtualenv -p python3 venv`

**Comment by sunfeng90** [comment]
我在python或者python3，可以inport redis，但是运行scrapy crawl jindong，就提示这个错误

**Comment by sunfeng90** [comment]
`virtualenv -p python3 venv` 然后 pip install -r requirements.txt，最后scrapy crawl jindong也是提示redis找不到

**Comment by samrayleung** [comment]
你可以先确定一下在 `venv` 里面用的是Python3 还是Python2, 就你上面的堆栈来看，你用的还是python 2
```
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in execute
cmd.crawler_process = CrawlerProcess(settings)
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 249, in init
super(CrawlerProcess, self).init(settings)
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 137, in init
self.spider_loader = _get_spider_loader(settings)
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/crawler.py", line 336, in _get_spider_loader
return loader_cls.from_settings(settings.frozencopy())
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 61, in from_settings
return cls(settings)
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 25, in init
self._load_all_spiders()
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
for module in walk_modules(name):
File "/Users/sunfeng/anaconda2/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
submod = import_module(fullpath)
File "/Users/sunfeng/anaconda2/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/Users/sunfeng/Project/Python/demo/jd_spider/jd/jd/spiders/jd.py", line 6, in 
```

**Comment by sunfeng90** [comment]
我venv里面的环境是3.7的哦。我不想在环境中耗费时间了。可以把你的venv发给我吗？我直接运行，然后学习你的代码。

**Comment by samrayleung** [comment]
>virtualenv -p python3 venv 然后 pip install -r requirements.txt

把 venv 删掉之后重试一遍，试试 `pip3 install -r requirements.txt` 。可能你用了系统级的pip. 我的env 可能有和操作系统相关的东西，不一定对你适用.

**Comment by sunfeng90** [comment]
貌似删除ven,然后pip3 install -r requirements.txt确实不提示刚开始的错误了。好像能爬虫了。。。。

**Comment by sunfeng90** [comment]
`2018-04-17 12:50:43 [scrapy.log] INFO: Dumping Scrapy stats:
{b'downloader/request_bytes': b'620',
 b'downloader/request_count': b'3',
 b'downloader/request_method_count/GET': b'3',
 b'downloader/response_bytes': b'29263',
 b'downloader/response_count': b'3',
 b'downloader/response_status_count/200': b'1',
 b'downloader/response_status_count/302': b'2',
 b'finish_reason': b'finished',
 b'finish_time': b'2018-04-17 04:50:43.005186',
 b'log_count/DEBUG': b'5',
 b'log_count/ERROR': b'1',
 b'log_count/INFO': b'8',
 b'memusage/max': b'67833856',
 b'memusage/startup': b'67833856',
 b'response_received_count': b'1',
 b'scheduler/dequeued/redis': b'3',
 b'scheduler/enqueued/redis': b'3',
 b'spider_exceptions/NameError': b'1',
 b'start_time': b'2018-04-17 04:50:36.730894'}
2018-04-17 12:50:43 [scrapy.core.engine] INFO: Spider closed (finished)` 爬虫完成了。谢谢你。
