### ISSUE TITLE
新手。。如何运行

### ISSUE THREAD

**Issue by mumutu66** [samrayleung/jd_spider#4]
好像没看到requirements.txt 望赐教。

**Comment by mumutu66** [comment]
。还以为-r可以自己遍历

**Comment by mumutu66** [comment]
安装完所有的依赖以及运行了graphite的docker
仍然出现类似
```
2017-09-26 11:51:22 [scrapy] INFO: Scrapy 1.2.0 started (bot: jd_comment)
2017-09-26 11:51:22 [scrapy] INFO: Overridden settings: {'BOT_NAME': 'jd_comment', 'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter', 'NEWSPIDER_MODULE': 'jd_comment.spiders', 'ROBOTSTXT_OBEY': True, 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'SPIDER_MODULES': ['jd_comment.spiders'], 'STATS_CLASS': 'jd_comment.statscol.graphite.RedisGraphiteStatsCollector'}
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/spiderloader.py", line 41, in load
    return self._spiders[spider_name]
KeyError: 'jd_commnet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/crawler.py", line 162, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/crawler.py", line 190, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/crawler.py", line 194, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/spiderloader.py", line 43, in load
    raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: jd_commnet'

```
`jd`那个相同  如果redis什么没有启动 会报错redis等错误 这个实在看不出是什么引起的
Scrapy 的版本从1.2尝试到1.4 no luck ORZ

**Comment by mumutu66** [comment]
1.4里面。。spider的名字好像要和运行的一致？  改成同样的名字就ok了。。

**Comment by samrayleung** [comment]
你有先去爬取商品的信息, 过了一段时间再去爬取评论的信息么? 其实这里两只不同的爬虫,一只是爬取商品信息, 一只是爬取商品评论信息的, 爬取评论的爬虫依赖于爬取商品的爬虫的. 你没看到`requirements.txt`,
是因为你没有到具体某一只爬虫的目录里面．其中的一部分路径如下
```
├── jd
│   ├── jd
│   │   ├── __init__.py
│   │   ├── items.py
│   │   ├── middlewares.py
│   │   ├── pipelines.py
│   │   ├── proxy_ip.txt
│   │   ├── requirements.txt
│   │   ├── settings.py
│   │   ├── spiders
│   │   ├── statscol
│   │   ├── utils
│   │   └── venv
```

**Comment by mumutu66** [comment]
@samrayleung  两个都一样 只是直接运行  我后来改变了 jd.py里面的name 成为jd就好了 而不是原来的jingdong。不知道是不是这个问题

**Comment by samrayleung** [comment]
应该是`scrapy crawl jindong`，文档有一点小问题．你那样修改也没问题．我更新一下文档
